Feat/nested layout
christojeffrey/software-visualization pull request #23
Opened 2024-02-01 15:56 UTC by Perry26

Implement nested lay-out

The inner lay-out is a radial lay-out, outer lay-out doesn't do much (yet). Michel suggested to try a tree layout on the outer layer

Bugs are still present when dragging nodes (not that is was bug-free anyway), But since the inner layout fixes the nodes in a circle, we might want to reconsider the expansion/contraction behaviour of the nodes.

Though there is still some work to do, it would be great if this could be merged to prevent further conflicts down the line.

2024-02-02 11:49 UTC, christojeffrey reviewed
otherwise seems fine

2024-02-02 11:49 UTC, christojeffrey commented on svelte/src/routes/v2/scripts/draw/index.ts
> +			.extent([
this should no longer be here right? @Adityapnn811

2024-02-02 12:59 UTC, Adityapnn811 requested changes
Don't forget about the zoom

2024-02-02 12:59 UTC, Adityapnn811 commented on svelte/src/routes/v2/scripts/draw/index.ts
> +			.extent([
Yes I removed it

2024-02-02 15:21 UTC, Perry26 commented
Should be fixed

2024-02-04 08:45 UTC, Adityapnn811 approved these changes

2024-02-07 11:53 UTC, merged